import { useState, useCallback } from "react";
import Head from "next/head";
import Map, {
  AttributionControl,
  FullscreenControl,
  GeolocateControl,
  Layer,
  Source,
  Marker,
} from "react-map-gl";
import * as turf from "@turf/turf";
import * as parkData from "../src/data/sb-parks.json";
import * as subwayData from "../src/data/subway.json";
import { Controls } from "../components/Controls";
import { Button } from "@chakra-ui/react";

const MAPBOX_TOKEN =
  "pk.eyJ1IjoidGtuaWdodDMxIiwiYSI6ImNsY2o4MmV4NDQ5aWIzcW1vNzdleHg2dXMifQ.Bb6nK9SLunI75I81QECNig";

// A circle of 5 mile radius of the Empire State Building
// const GEOFENCE = turf.circle([-74.0122106, 40.7467898], 5, { units: "miles" });

// const geojson = {
//   type: "Feature",
//   Geometry: {
//     type: "Polygon",
//     coordinates: [
//       [
//         [-67.13734351262877, 45.137451890638886],
//         [-66.96466, 44.8097],
//         [-68.03252, 44.3252],
//         [-69.06, 43.98],
//         [-70.11617, 43.68405],
//         [-70.64573401557249, 43.090083319667144],
//         [-70.75102474636725, 43.08003225358635],
//         [-70.79761105007827, 43.21973948828747],
//         [-70.98176001655037, 43.36789581966826],
//         [-70.94416541205806, 43.46633942318431],
//         [-71.08482, 45.3052400000002],
//         [-70.6600225491012, 45.46022288673396],
//         [-70.30495378282376, 45.914794623389355],
//         [-70.00014034695016, 46.69317088478567],
//         [-69.23708614772835, 47.44777598732787],
//         [-68.90478084987546, 47.184794623394396],
//         [-68.23430497910454, 47.35462921812177],
//         [-67.79035274928509, 47.066248887716995],
//         [-67.79141211614706, 45.702585354182816],
//         [-67.13734351262877, 45.137451890638886],
//       ],
//     ],
//   },
// };

const layers = [
  {
    id: "point",
    type: "circle",
    paint: {
      "circle-radius": 10,
      "circle-color": "#007cbf",
    },
  },
];

export default function Home() {
  const [viewState, setViewState] = useState({
    longitude: -74.0122106,
    latitude: 40.7467898,
    zoom: 11,
    bearing: 24,
  });

  const [isSubways, setSubways] = useState(true);
  const [isParks, setParks] = useState(true);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Map
        {...viewState}
        style={{ width: "100%", height: "100vh" }}
        onMove={(e) => setViewState(e.viewState)}
        mapStyle="mapbox://styles/tknight31/clcjiq8c1003v15t7fseghgtk"
        mapboxAccessToken={MAPBOX_TOKEN}
        pitch={60}
        attributionControl={false}
      >
        <AttributionControl customAttribution="I MADE THIS" />

        <Controls
          isSubways={isSubways}
          setSubways={setSubways}
          isParks={isParks}
          setParks={setParks}
        />

        {isParks &&
          parkData.features.map((park) => {
            return (
              <Marker
                key={park.properties.PARK_ID}
                longitude={park.geometry.coordinates[0]}
                latitude={park.geometry.coordinates[1]}
              >
                <div style={{ fontSize: "45px" }}>🛹</div>
              </Marker>
            );
          })}
        {isSubways &&
          subwayData.features.map((station) => {
            return (
              <Marker
                key={station.properties.objectid}
                longitude={station.geometry.coordinates[0]}
                latitude={station.geometry.coordinates[1]}
              >
                <div style={{ fontSize: "14px" }}>🚆</div>
              </Marker>
            );
          })}
      </Map>
    </>
  );
}
